### ISSUE TITLE
Can't send or Receive any Messages

### ISSUE THREAD

**Issue by jwdsoft** [kekelele/python_j2534#2]
Firstly I want to thank you for this great API
I'm using it to know more about the protocol 
so I'm trying all the different Api calls you have made
get devices and readversion and connect all of them work fine
but when I got into sending or receiving messages i got an error
This is when receiving
[ptOpen:STATUS_NOERROR]
[ptConnect:STATUS_NOERROR]
[ptReadMsgs:ERR_BUFFER_EMPTY]
[ptReadMsgs:ERR_BUFFER_EMPTY]

and when sending 
[ptOpen:STATUS_NOERROR]
[ptConnect:STATUS_NOERROR]
[0, 0, 1, 35, 0, 1, 2, 3, 4, 5, 6, 7]
[ptWtiteMsgs:ERR_TIMEOUT]
[ptDisconnect:STATUS_NOERROR]
[ptClose:STATUS_NOERROR]

(even though the protocol=can and baudrate=500k are good)
i'm using my arduino to send messages regularly on can with 500k baudrate but the J2534 doesn't pick up any message.

Any idea why this is happening ?

**Comment by jwdsoft** [comment]
I've made the sending part work
but the receive part still give timeout error :(

**Comment by kekelele** [comment]
Hi&nbsp;
Sorry I am on a business trip. So I can't help you now.&nbsp;
Please wait until tomorrow.

发自我的iPhone


------------------ Original ------------------

**Comment by jwdsoft** [comment]
Ok thank you I'm waiting for your reply

**Comment by jwdsoft** [comment]
Hello @kekelele Still waiting for your help
I'm still stuck at the receiving part :(
Thank you

**Comment by carkang** [comment]
Portocol.CAN mast be setting filter mask(0x0000000 and PASS_FILTER)

**Comment by DavidBejenar** [comment]
Спасибо.Я уже разобрался))Спасибо за то что вы сделали)

четверг, 31 декабря 2020 г. пользователь carkang <notifications@github.com>
написал:

**Comment by DavidBejenar** [comment]
Вам нужен анализатор Can сообщений.Так будет трудно понять что не так.Может
быть на самом деле нет сообщений.Покажите ваш код?

пятница, 27 августа 2021 г. пользователь carik-car ***@***.***>
написал:

**Comment by carik-car** [comment]
анализатор есть, понимание как работает кан шина тоже. вот столкнулся с этим языком впервые, передача в каншину есть, ответ от блока анализатором вижу, программа нет. 
код как код, от исходника не отличается, вопрос в том, что нет описания как настроить чтение нужного ид...
запрос 7е1 ответ на 7е9.

`#coding:utf-8
import J2534
from J2534.Define import *
import sys
import sys, time
J2534.SetErrorLog(True)


devices = J2534.getDevices()
for id in devices:
    print( id , devices[id])
J2534.setDevice(0)
ret, deviceID = J2534.ptOpen()
toolINFO = J2534.ptReadVersion(deviceID)
print(toolINFO)

try:
    index = int(sys.argv[1], base=10)
except:
    index = 0
J2534.setDevice(index)

ret, channelID = J2534.ptConnect(deviceID, ProtocolID.CAN, 0, BaudRate.B500K)

msg = J2534.ptTxMsg(ProtocolID.CAN, 0)
msg.setIDandData((0x7E1), [0x01,0x02,0x00,0x03,0x08,0x00,0x00,0x00])
J2534.ptWtiteMsgs(channelID, msg, 1, 100)
msg.setIDandData((0x7E1), [0xAA,0xBB,0xFF,0x13,0x14,0x15,0x16,0x17])
J2534.ptWtiteMsgs(channelID, msg, 1, 100)

ret, channelID = J2534.ptConnect(deviceID, ProtocolID.CAN, 0, BaudRate.B500K)


msg = J2534.ptRxMsg()

start = time.time()
while True:
    if time.time() - start > 1:
        break
    ret = J2534.ptReadMsgs(channelID, msg, 1, 10)
    if ret == 0:
        msg.show()

ret = J2534.ptDisconnect(channelID)
ret = J2534.ptClose(deviceID)`

**Comment by kekelele** [comment]
I will delete the python_j2534
